### ISSUE TITLE
Double click will give you a Ellipse

### ISSUE THREAD

**Issue by samcompu** [sandoche/Darkmode.js#24] opened 2019-11-08 14:50 UTC
![:)](https://i.loli.net/2019/11/08/wiaxGH3IvJtSjug.png)

**Comment by bdthemes** [comment] 2019-11-25 10:47
Same issue for me too!

**Comment by shahidul24** [comment] 2019-11-26 04:48
I Got also same Issue.

![image](https://user-images.githubusercontent.com/35867332/69600264-33b6ff80-103a-11ea-83a1-8f2955a87486.png)

**Comment by MrSkwiggs** [comment] 2019-12-06 14:55
Duplicate of #7

**Closed** 2019-12-11 10:26 UTC
